name = "LocksBenchmarks"
uuid = "c9853ddb-a9c6-4214-a076-5174e7e165c1"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Locks = "b2b8d39d-860c-47cc-b75e-a6e39294eaae"
SyncBarriers = "3986aa12-c984-439b-887a-f8545bea0e93"

[compat]
julia = "1.6"
